export class Repo {
  [key: string]: any

  name: string = ''
  owner: any = {}
  fork: boolean = false
  stargazers_count: number = 0
  updated_at: string = ''
}

  //  {
  //   "id": 232583252,
  //   "node_id": "MDEwOlJlcG9zaXRvcnkyMzI1ODMyNTI=",
  //   "name": "abesse",
  //   "full_name": "cherryApp/abesse",
  //   "private": false,
  //   "owner": {
  //     "login": "cherryApp",
  //     "id": 4568526,
  //     "node_id": "MDQ6VXNlcjQ1Njg1MjY=",
  //     "avatar_url": "https://avatars.githubusercontent.com/u/4568526?v=4",
  //     "gravatar_id": "",
  //     "url": "https://api.github.com/users/cherryApp",
  //     "html_url": "https://github.com/cherryApp",
  //     "followers_url": "https://api.github.com/users/cherryApp/followers",
  //     "following_url": "https://api.github.com/users/cherryApp/following{/other_user}",
  //     "gists_url": "https://api.github.com/users/cherryApp/gists{/gist_id}",
  //     "starred_url": "https://api.github.com/users/cherryApp/starred{/owner}{/repo}",
  //     "subscriptions_url": "https://api.github.com/users/cherryApp/subscriptions",
  //     "organizations_url": "https://api.github.com/users/cherryApp/orgs",
  //     "repos_url": "https://api.github.com/users/cherryApp/repos",
  //     "events_url": "https://api.github.com/users/cherryApp/events{/privacy}",
  //     "received_events_url": "https://api.github.com/users/cherryApp/received_events",
  //     "type": "User",
  //     "site_admin": false
  //   },
  //   "html_url": "https://github.com/cherryApp/abesse",
  //   "description": "Cool stuffs for the Abesse team.",
  //   "fork": false,
  //   "url": "https://api.github.com/repos/cherryApp/abesse",
  //   "forks_url": "https://api.github.com/repos/cherryApp/abesse/forks",
  //   "keys_url": "https://api.github.com/repos/cherryApp/abesse/keys{/key_id}",
  //   "collaborators_url": "https://api.github.com/repos/cherryApp/abesse/collaborators{/collaborator}",
  //   "teams_url": "https://api.github.com/repos/cherryApp/abesse/teams",
  //   "hooks_url": "https://api.github.com/repos/cherryApp/abesse/hooks",
  //   "issue_events_url": "https://api.github.com/repos/cherryApp/abesse/issues/events{/number}",
  //   "events_url": "https://api.github.com/repos/cherryApp/abesse/events",
  //   "assignees_url": "https://api.github.com/repos/cherryApp/abesse/assignees{/user}",
  //   "branches_url": "https://api.github.com/repos/cherryApp/abesse/branches{/branch}",
  //   "tags_url": "https://api.github.com/repos/cherryApp/abesse/tags",
  //   "blobs_url": "https://api.github.com/repos/cherryApp/abesse/git/blobs{/sha}",
  //   "git_tags_url": "https://api.github.com/repos/cherryApp/abesse/git/tags{/sha}",
  //   "git_refs_url": "https://api.github.com/repos/cherryApp/abesse/git/refs{/sha}",
  //   "trees_url": "https://api.github.com/repos/cherryApp/abesse/git/trees{/sha}",
  //   "statuses_url": "https://api.github.com/repos/cherryApp/abesse/statuses/{sha}",
  //   "languages_url": "https://api.github.com/repos/cherryApp/abesse/languages",
  //   "stargazers_url": "https://api.github.com/repos/cherryApp/abesse/stargazers",
  //   "contributors_url": "https://api.github.com/repos/cherryApp/abesse/contributors",
  //   "subscribers_url": "https://api.github.com/repos/cherryApp/abesse/subscribers",
  //   "subscription_url": "https://api.github.com/repos/cherryApp/abesse/subscription",
  //   "commits_url": "https://api.github.com/repos/cherryApp/abesse/commits{/sha}",
  //   "git_commits_url": "https://api.github.com/repos/cherryApp/abesse/git/commits{/sha}",
  //   "comments_url": "https://api.github.com/repos/cherryApp/abesse/comments{/number}",
  //   "issue_comment_url": "https://api.github.com/repos/cherryApp/abesse/issues/comments{/number}",
  //   "contents_url": "https://api.github.com/repos/cherryApp/abesse/contents/{+path}",
  //   "compare_url": "https://api.github.com/repos/cherryApp/abesse/compare/{base}...{head}",
  //   "merges_url": "https://api.github.com/repos/cherryApp/abesse/merges",
  //   "archive_url": "https://api.github.com/repos/cherryApp/abesse/{archive_format}{/ref}",
  //   "downloads_url": "https://api.github.com/repos/cherryApp/abesse/downloads",
  //   "issues_url": "https://api.github.com/repos/cherryApp/abesse/issues{/number}",
  //   "pulls_url": "https://api.github.com/repos/cherryApp/abesse/pulls{/number}",
  //   "milestones_url": "https://api.github.com/repos/cherryApp/abesse/milestones{/number}",
  //   "notifications_url": "https://api.github.com/repos/cherryApp/abesse/notifications{?since,all,participating}",
  //   "labels_url": "https://api.github.com/repos/cherryApp/abesse/labels{/name}",
  //   "releases_url": "https://api.github.com/repos/cherryApp/abesse/releases{/id}",
  //   "deployments_url": "https://api.github.com/repos/cherryApp/abesse/deployments",
  //   "created_at": "2020-01-08T14:33:55Z",
  //   "updated_at": "2022-01-31T08:01:12Z",
  //   "pushed_at": "2022-03-02T09:34:46Z",
  //   "git_url": "git://github.com/cherryApp/abesse.git",
  //   "ssh_url": "git@github.com:cherryApp/abesse.git",
  //   "clone_url": "https://github.com/cherryApp/abesse.git",
  //   "svn_url": "https://github.com/cherryApp/abesse",
  //   "homepage": null,
  //   "size": 11053,
  //   "stargazers_count": 3,
  //   "watchers_count": 3,
  //   "language": "TypeScript",
  //   "has_issues": true,
  //   "has_projects": true,
  //   "has_downloads": true,
  //   "has_wiki": true,
  //   "has_pages": false,
  //   "forks_count": 0,
  //   "mirror_url": null,
  //   "archived": false,
  //   "disabled": false,
  //   "open_issues_count": 48,
  //   "license": null,
  //   "allow_forking": true,
  //   "is_template": false,
  //   "topics": [],
  //   "visibility": "public",
  //   "forks": 0,
  //   "open_issues": 48,
  //   "watchers": 3,
  //   "default_branch": "master"
  // },